### ISSUE TITLE
Doesn't work: Platform dependent initialization failed

### ISSUE THREAD

**Issue by Wikunia** [kenperlin/chalktalk#31]
I can draw stuff but nothing gets recognized.
I'm using google-chrome on ArchLinux
When I run the command `./run.linux` I get:
```
[3117:3159:1106/205432.945107:ERROR:browser_gpu_channel_host_factory.cc(108)] Failed to launch GPU process.
Created new window in existing browser session.
```

In Google DevTools I get:
```
THREE.WebGLRenderer 70
midi.js:15 Something went wrong while requesting MIDI access: InvalidStateError: Platform dependent initialization failed.
```

**Comment by Wikunia** [comment]
It works if I use space bar and then interpret. I thought that works automatically

**Comment by KTRosenberg** [comment]
@Wikunia Were you able to resolve the issue? Pressing spacebar shouldn't be required, so we will look into the issue as soon as possible.
