### ISSUE TITLE
permissions error

### ISSUE THREAD

**Issue by stephenlewis1949** [kenperlin/chalktalk#34]
Sorry for the simple question, but when I try to clone using 
git clone git@github.com:kenperlin/chalktalk.git --depth=1
I get a permissions error.  Not a frequent user of git, so perhaps a simple fix for this?

thanks 

Steve Lewis

**Comment by KTRosenberg** [comment]
`git clone https://github.com/kenperlin/chalktalk.git --depth=1` is the correct command. I will update the wiki.

**Comment by stephenlewis1949** [comment]
Thanks.  That seemed to work for the cloning, but the cd and install
generated these errors.
Thanks for any further help.
Steve

Last login: Wed Nov  8 12:27:03 on ttys000

Stephens-MacBook-Air-2:~ steve$ https://github.com/kenperlin/chalktalk.git
--depth=1

-bash: https://github.com/kenperlin/chalktalk.git: No such file or directory

Stephens-MacBook-Air-2:~ steve$ git clone
https://github.com/kenperlin/chalktalk.git --depth=1

Cloning into 'chalktalk'...

remote: Counting objects: 195, done.

remote: Compressing objects: 100% (190/190), done.

remote: Total 195 (delta 5), reused 51 (delta 2), pack-reused 0

Receiving objects: 100% (195/195), 8.46 MiB | 13.30 MiB/s, done.

Resolving deltas: 100% (5/5), done.

Checking connectivity... done.

Stephens-MacBook-Air-2:~ steve$ cd ./chalktalk/server/

Stephens-MacBook-Air-2:server steve$ npm install

Error: Cannot find module './lib/cookies'

    at Function.Module._resolveFilename (module.js:326:15)

    at Function.Module._load (module.js:277:25)

    at Module.require (module.js:354:17)

    at require (internal/module.js:12:17)

    at Object.<anonymous>
(/usr/local/lib/node_modules/npm/node_modules/request/index.js:18:29)

    at Module._compile (module.js:410:26)

    at Object.Module._extensions..js (module.js:417:10)

    at Module.load (module.js:344:32)

    at Function.Module._load (module.js:301:12)

    at Module.require (module.js:354:17)

    at require (internal/module.js:12:17)

npm ERR! Darwin 14.5.0

npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"

npm ERR! node v4.2.6

npm ERR! npm  v2.14.12

npm ERR! code MODULE_NOT_FOUND


npm ERR! Cannot find module './lib/cookies'

npm ERR!

npm ERR! If you need help, you may report this error at:

npm ERR!     <https://github.com/npm/npm/issues>

Stephens-MacBook-Air-2:server steve$ cd ./chalktalk/server

-bash: cd: ./chalktalk/server: No such file or directory

Stephens-MacBook-Air-2:server steve$ ls

editor.html main.js npm-debug.log package.json

Stephens-MacBook-Air-2:server steve$ cd ../chalktalk/server

-bash: cd: ../chalktalk/server: No such file or directory

Stephens-MacBook-Air-2:server steve$ cd chalktalk

-bash: cd: chalktalk: No such file or directory

Stephens-MacBook-Air-2:server steve$ cd..

-bash: cd..: command not found

Stephens-MacBook-Air-2:server steve$ ls

editor.html main.js npm-debug.log package.json

Stephens-MacBook-Air-2:server steve$ npm install

Error: Cannot find module './lib/cookies'

    at Function.Module._resolveFilename (module.js:326:15)

    at Function.Module._load (module.js:277:25)

    at Module.require (module.js:354:17)

    at require (internal/module.js:12:17)

    at Object.<anonymous>
(/usr/local/lib/node_modules/npm/node_modules/request/index.js:18:29)

    at Module._compile (module.js:410:26)

    at Object.Module._extensions..js (module.js:417:10)

    at Module.load (module.js:344:32)

    at Function.Module._load (module.js:301:12)

    at Module.require (module.js:354:17)

    at require (internal/module.js:12:17)

npm ERR! Darwin 14.5.0

npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"

npm ERR! node v4.2.6

npm ERR! npm  v2.14.12

npm ERR! code MODULE_NOT_FOUND


npm ERR! Cannot find module './lib/cookies'

npm ERR!

npm ERR! If you need help, you may report this error at:

npm ERR!     <https://github.com/npm/npm/issues>

Stephens-MacBook-Air-2:server steve$

**Comment by KTRosenberg** [comment]
Is Nodejs installed? https://nodejs.org/en/

**Comment by stephenlewis1949** [comment]
Thanks.  I thought I had it installed, but must have removed it for some
reason, or I had an older version?  Anyway, it now runs, thanks

Still have to get acquainted with the operation of the program itself.  Are
there any online interactive working demos or local ones I could install?
Did I miss that?

**Comment by KTRosenberg** [comment]
We haven't created interactive demos yet, but pressing <kbd>Space</kbd> within Chalktalk toggles help mode, which shows what gestures and options are available. (That can be helpful for beginners.) We are actively thinking about and experimenting with ways to improve the first-time use experience. As for sketch creation, take a look at this [wiki page](https://github.com/kenperlin/chalktalk/wiki/Creating-a-Sketch) and [this starter file](https://github.com/kenperlin/chalktalk/blob/master/sketch_templates/beginner_template_stub.js), which should help if you want to try playing with making sketches.
