### ISSUE TITLE
RangeError: "port" argument must be >= 0 and < 65536

### ISSUE THREAD

**Issue by fredhampton** [kenperlin/chalktalk#36]
I m trying to have Chalktalk load/start with in an app that I'am developing.
I have added this to the background-process.js file like this

require('./chalktalk/server/main.js')

When the app starts Chalktalk throws the following error 

App threw an error during load
RangeError: "port" argument must be >= 0 and < 65536

Is there a way to start Chalktalk server using require ?
Is it possible to start Chalktalk sever without it launching chrome ?

Thanks

**Comment by Kronopath** [comment]
To answer your second question: yes, if you look in the `run.sh` script, you'll see that it's just running `node server/main.js` (which actually runs the server) and then opening Chrome afterwards. There's nothing special about it.

To answer your first question: Chalktalk's server code isn't a library and as such isn't meant to be used with `require`. You'll have to find another way to start the server.
